-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.about_info (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  mission_fr text,
  mission_en text,
  vision_fr text,
  vision_en text,
  pedagogy_theoretical_fr text,
  pedagogy_theoretical_en text,
  pedagogy_practical_fr text,
  pedagogy_practical_en text,
  pedagogy_evaluation_fr text,
  pedagogy_evaluation_en text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT about_info_pkey PRIMARY KEY (id)
);
CREATE TABLE public.about_values (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title_fr character varying NOT NULL,
  title_en character varying NOT NULL,
  description_fr text,
  description_en text,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT about_values_pkey PRIMARY KEY (id)
);
CREATE TABLE public.center_info (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  center_id uuid NOT NULL UNIQUE,
  mission_fr text,
  mission_en text,
  vision_fr text,
  vision_en text,
  history_fr text,
  history_en text,
  social_facebook character varying,
  social_instagram character varying,
  social_linkedin character varying,
  social_twitter character varying,
  other_phones jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT center_info_pkey PRIMARY KEY (id),
  CONSTRAINT center_info_center_id_fkey FOREIGN KEY (center_id) REFERENCES public.centers(id)
);
CREATE TABLE public.center_partners (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  center_id uuid NOT NULL,
  name_fr character varying NOT NULL,
  name_en character varying NOT NULL,
  logo character varying,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT center_partners_pkey PRIMARY KEY (id),
  CONSTRAINT center_partners_center_id_fkey FOREIGN KEY (center_id) REFERENCES public.centers(id)
);
CREATE TABLE public.center_stats (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  center_id uuid NOT NULL,
  value character varying NOT NULL,
  label_fr character varying NOT NULL,
  label_en character varying NOT NULL,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT center_stats_pkey PRIMARY KEY (id),
  CONSTRAINT center_stats_center_id_fkey FOREIGN KEY (center_id) REFERENCES public.centers(id)
);
CREATE TABLE public.center_values (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  center_id uuid NOT NULL,
  title_fr character varying NOT NULL,
  title_en character varying NOT NULL,
  description_fr text,
  description_en text,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT center_values_pkey PRIMARY KEY (id),
  CONSTRAINT center_values_center_id_fkey FOREIGN KEY (center_id) REFERENCES public.centers(id)
);
CREATE TABLE public.centers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  slug character varying NOT NULL UNIQUE,
  name_fr character varying NOT NULL,
  name_en character varying NOT NULL,
  full_name_fr character varying NOT NULL,
  full_name_en character varying NOT NULL,
  description_fr text,
  description_en text,
  logo character varying,
  primary_color character varying DEFAULT '#3B82F6'::character varying,
  secondary_color character varying DEFAULT '#8B5CF6'::character varying,
  location character varying,
  email character varying,
  phone character varying,
  whatsapp character varying,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT centers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contacts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  subject character varying,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contacts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.formation_careers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  formation_id uuid NOT NULL,
  career_fr text NOT NULL,
  career_en text NOT NULL,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT formation_careers_pkey PRIMARY KEY (id),
  CONSTRAINT formation_careers_formation_id_fkey FOREIGN KEY (formation_id) REFERENCES public.formations(id)
);
CREATE TABLE public.formation_skills (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  formation_id uuid NOT NULL,
  skill_fr text NOT NULL,
  skill_en text NOT NULL,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT formation_skills_pkey PRIMARY KEY (id),
  CONSTRAINT formation_skills_formation_id_fkey FOREIGN KEY (formation_id) REFERENCES public.formations(id)
);
CREATE TABLE public.formations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  slug character varying NOT NULL UNIQUE,
  title_fr character varying NOT NULL,
  title_en character varying NOT NULL,
  short_description_fr text,
  short_description_en text,
  full_description_fr text,
  full_description_en text,
  duration character varying,
  level character varying,
  icon character varying,
  image character varying,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  center_id uuid,
  center_slug character varying,
  image_url text,
  CONSTRAINT formations_pkey PRIMARY KEY (id),
  CONSTRAINT formations_center_id_fkey FOREIGN KEY (center_id) REFERENCES public.centers(id)
);
CREATE TABLE public.gallery (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title character varying,
  url character varying NOT NULL,
  category character varying,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gallery_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying NOT NULL,
  formation_id uuid,
  message text,
  created_at timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  gender character varying,
  place_of_birth character varying,
  nationality character varying,
  whatsapp character varying,
  postal_code character varying,
  country character varying DEFAULT 'Cameroun'::character varying,
  father_name character varying,
  father_profession character varying,
  father_phone character varying,
  mother_name character varying,
  mother_profession character varying,
  mother_phone character varying,
  emergency_contact_name character varying,
  emergency_contact_relationship character varying,
  emergency_contact_phone character varying,
  desired_formation character varying,
  academic_level character varying,
  last_school_attended character varying,
  last_diploma_obtained character varying,
  diploma_year character varying,
  preferred_start_date character varying,
  is_first_time_student boolean DEFAULT true,
  has_previous_medical_training boolean DEFAULT false,
  languages_spoken text,
  has_disabilities boolean DEFAULT false,
  disability_description text,
  special_needs text,
  motivation_message text,
  career_goals text,
  why_this_formation text,
  has_birth_certificate boolean DEFAULT false,
  has_diploma boolean DEFAULT false,
  has_photos boolean DEFAULT false,
  has_id_card boolean DEFAULT false,
  documents_notes text,
  admin_notes text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  source character varying DEFAULT 'website'::character varying,
  ip_address character varying,
  user_agent text,
  updated_at timestamp with time zone DEFAULT now(),
  address text NOT NULL,
  city text NOT NULL,
  date_of_birth date,
  CONSTRAINT inscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT inscription_submissions_formation_id_fkey FOREIGN KEY (formation_id) REFERENCES public.formations(id)
);
CREATE TABLE public.news (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  slug character varying NOT NULL UNIQUE,
  category character varying CHECK (category::text = ANY (ARRAY['event'::character varying, 'announcement'::character varying, 'success'::character varying]::text[])),
  image character varying,
  published_date date NOT NULL,
  title_fr character varying NOT NULL,
  title_en character varying NOT NULL,
  excerpt_fr text,
  excerpt_en text,
  content_fr text,
  content_en text,
  is_published boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT news_pkey PRIMARY KEY (id)
);
CREATE TABLE public.partners (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name_fr character varying NOT NULL,
  name_en character varying NOT NULL,
  logo character varying,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT partners_pkey PRIMARY KEY (id)
);
CREATE TABLE public.site_content (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  key character varying NOT NULL UNIQUE,
  category character varying NOT NULL,
  section character varying,
  content_fr text NOT NULL,
  content_en text NOT NULL,
  description text,
  content_type character varying DEFAULT 'text'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT site_content_pkey PRIMARY KEY (id)
);
CREATE TABLE public.site_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key character varying NOT NULL UNIQUE,
  url text NOT NULL,
  alt_fr text NOT NULL,
  alt_en text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT site_images_pkey PRIMARY KEY (id)
);
CREATE TABLE public.site_info (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  full_name character varying NOT NULL,
  description text,
  location character varying,
  email character varying,
  phone character varying,
  whatsapp character varying,
  fixed_line character varying,
  social_facebook character varying,
  social_instagram character varying,
  social_linkedin character varying,
  social_twitter character varying,
  other_phones jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  full_name_fr character varying,
  full_name_en character varying,
  description_fr text,
  description_en text,
  location_fr character varying,
  location_en character varying,
  CONSTRAINT site_info_pkey PRIMARY KEY (id)
);
CREATE TABLE public.stats (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  value character varying NOT NULL,
  label_fr character varying NOT NULL,
  label_en character varying NOT NULL,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stats_pkey PRIMARY KEY (id)
);
CREATE TABLE public.videos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title character varying NOT NULL,
  description text,
  url character varying NOT NULL,
  thumbnail_url character varying,
  duration character varying,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT videos_pkey PRIMARY KEY (id)
);